config/routes.rb
RailsMoviesLab::Application.routes.draw do
  get "actors/index"

  get "actors/show"

  get '/movies/search' => 'movies#search', as: 'movie_search'
  get '/movies' => 'movies#index'
  post 'movies/:id/save' => 'movies#save', as: 'save'
  get 'movies/saved' => 'movies#saved', as: 'saved'
  get '/movies/favorites' => 'movies#favorites', as: 'favorite_movies'
  post '/movies/:id/add_favorite' => 'movies#add_favorite', as: 'add_favorite'
  root :to => 'welcome#index'
  resources :movies

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :movies
  attr_accessible :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :actors
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET
  # /movies/search
  # movies_search path
  def search
    if params[:movie].nil?
    else
      @movies = Imdb::Search.new(params[:movie]).movies
    end
      render "index"
  end

  # GET
  def show
    @movie = Imdb::Movie.new(params[:id])
  end

  def save
    @movie = Imdb::Movie.new(params[:id])
    movie = Movie.new
    movie.title = @movie.title
    movie.year = @movie.year
    movie.plot = @movie.plot
    movie.mpaa_rating = @movie.mpaa_rating
    movie.rating = 50
    movie.save
    redirect_to saved_path

    actors = @movie.cast_members[0..2]
    actors.each do |actor|
      new_actor = Actor.find_or_create_by_name(actor)

     movie.actors << new_actor
    end
  end

  def saved
    @movies = Movie.all
  end

  # Post
  # /
  def favorites
    @movie = Imdb::Movie.new(params[:id])
    movie = Movie.new
    movie.title = @movie.title
    # movie.year = @movie.year
    movie.plot = @movie.plot
    movie.mpaa_rating = @movie.mpaa_rating
    movie.rating = 100
    movie.save
    redirect_to saved_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

  def index
  end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/actors/index.html.erb
<h1>Actors#index</h1>
<p>Find me in app/views/actors/index.html.erb</p>

app/views/actors/show.html.erb
<h1>Actors#show</h1>
<p>Find me in app/views/actors/show.html.erb</p>

app/views/application/_navbar.html.erb
 <nav>
    <%= link_to("Home", root_path) %> |
    <%= link_to("Search Movies", movie_search_path) %> |
    <%= link_to("Saved Movies", saved_path) %> |
    <%= link_to("Favorite Movies", favorite_movies_path) %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMoviesLab</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'navbar' %>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<h1>Search Movies</h1>

<form action="/movies/search" method="get">
  <input type="string" name="movie" placeholder="Movie Title">
  <button>Search</button>
</form>

<% if @movies.nil? %>
<% else %>
<ul>
  <% @movies.each do |movie| %>
    <li> <%= link_to movie.title, movie.id %> </li>
  <% end %>
 </ul>
<% end %>

app/views/movies/saved.html.erb
<h1>Saved Movies</h1>

<% @movies.each do |movie| %>
<%= movie.title %>
<% end %>

app/views/movies/show.html.erb
<b>Movie Title:</b> <%= @movie.title %></br>
</br>
<b>Date Released:</b> <%= @movie.year %></br>
</br>
<b>Plot:</b> <%= @movie.plot %></br>
</br>
<b>MPAA Rating:</b> <%= @movie.mpaa_rating %></br>
</br>
<b>Rating:</b> <%= @movie.rating %></br>


<%= button_to "Save", save_path %> <%= button_to "Favorite", add_favorite_path %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>Thanks for visiting Tom's Movie Database.</p>
<p>Please feel free to save your faviorte movies!<p>